---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      version: 17.1.3
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: monitoring
  values:
    alertmanager:
      enabled: true
    defaultRules:
      create: true
      rules:
        alertmanager: true
        etcd: false
        general: true
        k8s: true
        kubeApiserver: true
        kubeApiserverAvailability: true
        kubeApiserverError: true
        kubeApiserverSlos: true
        kubePrometheusGeneral: true
        kubePrometheusNodeAlerting: true
        kubePrometheusNodeRecording: true
        kubeScheduler: false
        kubeStateMetrics: true
        kubelet: true
        kubernetesAbsent: true
        kubernetesApps: true
        kubernetesResources: true
        kubernetesStorage: true
        kubernetesSystem: true
        network: true
        node: true
        prometheus: true
        prometheusOperator: true
        time: true
    grafana:
      adminPassword: prom-operator
      enabled: true
    kubeEtcd:
      enabled: false
    kubeScheduler:
      enabled: false
    prometheus:
      enabled: true
    prometheusOperator:
      enabled: true

